### ISSUE TITLE
Add Items test

### ISSUE THREAD

**Issue by ashakhatri007** [ashakhatri007/CSC510_Group25_Project1#13]

**Comment by ashakhatri007** [comment]
Created new test class for Ingredient tests. Added UTs for same

**Comment by Neelkanth7** [comment]
Its good practice to link PRs with issue. Helped to understand exactly what you have implemented. Let's make this as standard and discuss this in our group meeting for other members to follow

**Comment by ashakhatri007** [comment]
Sure.!
