### ISSUE TITLE
Add style checkers for qty_calc

### ISSUE THREAD

**Issue by ashakhatri007** [ashakhatri007/CSC510_Group25_Project1#24]

**Comment by ashakhatri007** [comment]
Added maven plugin for style checker

**Comment by divyankgupta23** [comment]
Hey this works perfectly. Did you also try any other open source style checkers

**Comment by ashakhatri007** [comment]
I could only find this plugin. We can add customized rules but I am thinking to keep this as part of future To-do items

**Comment by Neelkanth7** [comment]
Yeah leaving it as a future To-do item seems a nice idea.
