### ISSUE TITLE
Setup new UI for the Website

### ISSUE THREAD

**Issue by lorenzs2908** [ashakhatri007/CSC510_Group25_Project1#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by divyankgupta23** [comment]
@lorenzs2908 could you share a demo link of the look and feel of the UI. Thanks!

**Comment by ashakhatri007** [comment]
I think we were retaining the look as it was before. @lorenzs2908 do you have any more ideas around same?
