### ISSUE TITLE
Get latest zenodo DOI badge

### ISSUE THREAD

**Issue by ashakhatri007** [ashakhatri007/CSC510_Group25_Project1#28]

**Comment by ashakhatri007** [comment]
Created new Zenodo badge by pushing a latest release for the project

**Comment by ashakhatri007** [comment]
Zenodo badge can be found here: https://zenodo.org/record/5590643#.YXHOD9nMK3I

**Comment by Neelkanth7** [comment]
Yeah , this looks fine
