### ISSUE TITLE
Implement Notification Functionality(Backend)

### ISSUE THREAD

**Issue by hetthakkar** [ashakhatri007/CSC510_Group25_Project1#63]
- Create API that fetches inventory items that are about to expire

- Create API that fetches inventory items that are currently expired

**Comment by divyankgupta23** [comment]
Also please check what all existing userRepository features we can use to implement it.

**Comment by ashakhatri007** [comment]
@hetthakkar please link the PR to this, so that we can discuss this in our next meet.

**Comment by ashakhatri007** [comment]
Notification functionality looks good.
