### ISSUE TITLE
Implement Notification Functionality(Frontend)

### ISSUE THREAD

**Issue by hetthakkar** [ashakhatri007/CSC510_Group25_Project1#64]
- Fetch inventory items that have expired and are about to expire and display them

**Comment by Neelkanth7** [comment]
@hetthakkar do we plan to use inventory APIs to populate UI here?

**Comment by ashakhatri007** [comment]
Tried out the Notification tab, good to see that it is now dynamically giving notifications as per inventory table in database which was expected.
